### ISSUE TITLE
print_sexp writes beyond end of buffer

### ISSUE THREAD

**Issue by mobileink** [mjsottile/sfsexp#2]
I'm putting sfsexp to good use, thanks.

This looks like a bug.  Code edited  for brevity:

```
const int bufsz = 5;
char buf[bufsz];
sexp_t *sx = NULL;

... read and parse a long sexp ...

size_t len = print_sexp(buf, sizeof(buf), sx);
log_debug("sizeof(buf): %d", sizeof(buf));
log_debug("printed %d bytes of sexp", len);
log_info("sexp: '%s'", buf);
log_debug("sexp_errno: %d", sexp_errno);

output:

sizeof(buf): 5
printed 7 bytes of sexp
sexp: '((ver))'
sexp_errno: 8   /* SEXP_ERR_BUFFER_FULL */
```

**Comment by mjsottile** [comment]
Good to hear that the library is useful!  I'm curious how people seem to be finding it lately since I've seen an increase in activity.

Yup - that looks like a bug that's been lurking in the library for going on 20 years.  Looking at that code I see a couple bugs - I fixed most of them with a simple change, but need to look a bit more closely at the SEXP_BINARY case to repair what I believe is a bug there too.  I should be able to push an update addressing this issue soon.

For reference, I used the following modified ctest.c as a reproducer:

```
#include <stdio.h>
#include "sexp.h"
#include <sys/time.h>
#include <time.h>
#include <assert.h>
#include <string.h>

#define RAWSTRING "(i am the test '(expression) \"with\" 'weird atoms)\0"

int main(int argc, char **argv) {
  sexp_t *sx;
  unsigned int len;
  pcont_t *pc = NULL;
  char outbuf[6];
  char inbuf[256];
  
  strcpy(inbuf,RAWSTRING);
  len = strlen(inbuf);
  
  pc = cparse_sexp(inbuf,len,pc);
  assert(pc != NULL);
  sx = pc->last_sexp;
  outbuf[5] = '\0';
  print_sexp(outbuf,5,sx);
  destroy_sexp(sx);
  destroy_continuation(pc);
  
  printf("%s\n",outbuf);
  printf("sexp_errno: %d\n", sexp_errno);
  sexp_cleanup();

  exit(EXIT_SUCCESS);
}
```

**Comment by mjsottile** [comment]
I believe that I've fixed the bug with a macro that makes sure the buffer size tests are performed everywhere that they should, and aborts appropriately when there is a problem.
