### ISSUE TITLE
Thread safety?

### ISSUE THREAD

**Issue by ether42** [mjsottile/sfsexp#21]
Hey,

Is sfsexp supposed to be thread safe or are users of the library supposed to disable the problematic features?

For example, with `_NO_MEMORY_MANAGEMENT_` disabled (the default), sfsexp isn't thread safe and none of its users will be: the global variable [faststack_t *pd_cache](https://github.com/mjsottile/sfsexp/blob/8222bf57c4e9ab3bedf6227df5ed6a19588dfa20/src/parser.c#L81) isn't protected which can lead to a null pointer dereference when used from multiple threads:
```
  #0  0x00007fc19ce20861 in pd_allocate () at parser.c:283
  #1  0x00007fc19ce21778 in cparse_sexp (str=0x7fc194018c40 "(from )", len=7, lc=0x0) at parser.c:863
  #2  0x00007fc19ce20c50 in parse_sexp (s=0x7fc194018c40 "(from )", len=7) at parser.c:486
  #3  0x00007fc19ce6f8a8 in _notmuch_sexp_string_to_xapian_query (notmuch=0x7fc194003120, querystr=0x7fc194018bd0 "(from )", output=...) at lib/parse-sexp.cc:723
  #4  0x00007fc19ce5e93f in _notmuch_query_ensure_parsed_sexpr (query=0x7fc1940147b0) at lib/query.cc:240
  #5  0x00007fc19ce5e997 in _notmuch_query_ensure_parsed (query=0x7fc1940147b0) at lib/query.cc:258
  #6  0x00007fc19ce5ed89 in _notmuch_query_search_documents (query=0x7fc1940147b0, type=0x7fc19ce78af6 "mail", out=0x7fc19bd3bcc0) at lib/query.cc:362
  #7  0x00007fc19ce5ed2f in notmuch_query_search_messages (query=0x7fc1940147b0, out=0x7fc19bd3bcc0) at lib/query.cc:350
  ...
```
I believe it's because [`if (empty_stack(pd_cache))`](https://github.com/mjsottile/sfsexp/blob/8222bf57c4e9ab3bedf6227df5ed6a19588dfa20/src/parser.c#L270) is racy and [later on](https://github.com/mjsottile/sfsexp/blob/8222bf57c4e9ab3bedf6227df5ed6a19588dfa20/src/parser.c#L283) the invariant doesn't hold anymore (l == NULL).

I've no idea if clients are supposed to tweak `_NO_MEMORY_MANAGEMENT_` but it's not necessarily feasible (as the distribution might compile the library separately).

Some context on [Notmuch's mailing list](https://nmbug.notmuchmail.org/nmweb/show/20230225174601.3394923-1-kevin%40boula.in).

**Comment by mjsottile** [comment]
I believe you are correct - the project from which the library was extracted wasn't threaded and instead managed multiple streams via select and per-stream continuations.  Those reasons are largely historical and irrelevant these days (I think the parent project has been mostly dead for at least 15 years).  I'm not sure the caching/memory limiting is valuable for most applications outside some niche cases, so an easy fix would be to switch the default to _NO_MEMORY_MANAGEMENT_ and make toggling it an explicit choice like "--enable-thread-unsafe-memory-management" that makes it clear what you're getting.  Wrapping the globals with locks would be fine too, although to maintain portability outside the POSIX world I'd have to have versions that work with more than just pthreads.

I just got back from being out for a while, so I have to deal with some work backlog at the moment.  If anyone is eager and wants to send pull requests in the meantime, that's fine with me.  Otherwise it'll be a week or two before I get around to making updates.

**Comment by ether42** [comment]
> so an easy fix would be to switch the default to NO_MEMORY_MANAGEMENT and make toggling it an explicit choice like "--enable-thread-unsafe-memory-management" that makes it clear what you're getting

Sounds good and I'd say the least surprising too (particularly for users and packagers: it'd be a shame to ask everyone [packaging](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/sfsexp/default.nix) the library to switch it off just to get notmuch to be thread safe). Sent #23.

> although to maintain portability outside the POSIX

Sadly I'm not too familiar with that, especially if you're talking about less 'mainstream' platforms, from the readme I gather this has been developed for something akin to supercomputers?.

**Comment by mjsottile** [comment]
Thanks for the pull request and apologies for the delay.  I'm reviewing and testing it today/tomorrow and should have this resolved shortly.  I want to revisit some of the related code outside the pull request in the library as well just to make sure I'm not missing anything important that is related to the memory management code.

Re: threading + portability.  The project originated on supercomputing systems that can have strange features, although lately most of them run some variant of Linux.  I still encounter unusual systems in the embedded space though.

**Comment by mjsottile** [comment]
I reviewed and approved the pull request - I just tweaked the README slightly so the example CLFAGS used the only other -D that the library recognizes (_SEXP_LIMIT_MEMORY_).  Thank you very much for the time and effort to send the patches - that was useful given my current workload.
